-- GMAT Official Guide book practice. Question CONTENT is not stored here: it is
-- served at runtime from data/gmat-og-questions.json (gitignored, regenerated by
-- the extraction pipeline). These tables hold the user's answers only, exactly
-- as lsat_attempts / lsat_sessions do for the LSAT track.
--
-- question_id is the pool's stable id ('OG13-CR-56' = book, subject, printed
-- question number). It survives regeneration of the JSON as long as the book and
-- printed number are unchanged, which is what makes it safe as a foreign key to
-- a file rather than a table.
CREATE TABLE IF NOT EXISTS og_attempts (
  id              integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  question_id     text NOT NULL,
  book_code       text NOT NULL,
  kind            text NOT NULL,
  user_answer     text NOT NULL,
  correct_answer  text,
  is_correct      integer,
  confidence      text,
  time_ms         integer,
  session_id      integer,
  attempted_at    timestamptz NOT NULL DEFAULT now(),
  mistake_type    text,
  notes           text
);

-- An OG session is built from FILTERS, not from a question range, so it stores
-- the resolved id list and the builder payload instead of first/last question.
CREATE TABLE IF NOT EXISTS og_sessions (
  id            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  set_label     text,
  mode          text,
  filters       text,
  question_ids  text,
  started_at    timestamptz NOT NULL DEFAULT now(),
  completed_at  timestamptz
);

CREATE INDEX IF NOT EXISTS idx_og_attempts_question ON og_attempts(question_id);
CREATE INDEX IF NOT EXISTS idx_og_attempts_session  ON og_attempts(session_id);
CREATE INDEX IF NOT EXISTS idx_og_sessions_started  ON og_sessions(started_at DESC);

-- Redoing a question is the point of the seen/wrong filter, so the uniqueness is
-- per (question, SESSION) — a new session always creates a fresh history row.
-- Within one session the builder guarantees each question appears once, and this
-- index is what makes re-submitting an answer in that session idempotent.
CREATE UNIQUE INDEX IF NOT EXISTS uq_og_attempts_session_q
  ON og_attempts(question_id, session_id);
