// Reader and index over data/gmat-og-questions.json — the GMAT Official Guide
// CR/RC question pool extracted from the three OG PDFs.
//
// The file is gitignored and regenerated by the extraction pipeline (see
// CLAUDE.md, "GMAT OG verbal practice"). It is read ONCE and cached in-process,
// so the API must be restarted after regenerating it — the same gotcha the LSAT
// track has.
//
// Only questions flagged `usable` are exposed. A question is usable when it is
// answerable as rendered: a complete stem, five non-empty choices, an undisputed
// key, and for RC a passage. A missing explanation is not a defect — 100 of the
// pool's 368 questions are keyed but unenriched, and they practice fine.

const fs = require('fs');
const path = require('path');

const POOL_PATH = path.join(__dirname, '..', 'data', 'gmat-og-questions.json');

// Questions whose explanation was dropped carry no type label. They stay
// selectable in the builder under this bucket rather than disappearing from it.
const UNLABELED = '(unlabeled)';

// The derived question type (Assumption, Weaken, Main Idea, …) sits alongside
// the book's own label rather than replacing it: the OG's label is the
// authoritative one, and the derived type is the one worth drilling by. About
// 7% of questions match no rule and keep this bucket, which stays selectable.
const UNCLASSIFIED = '(unclassified)';

// Difficulty reads as a scale, not a word list, so it keeps its own order
// instead of sorting alphabetically into Easy / Hard / Medium.
const DIFFICULTY_ORDER = ['Easy', 'Medium', 'Hard'];

// Mirrors the rule order in client/src/lib/questionType.mjs. Kept as a plain
// list rather than imported because that module is ESM and this reader is
// loaded synchronously on every request; a drifting list only mis-sorts the
// builder's chips, where a drifting rule table would mis-label questions.
const QUESTION_TYPE_ORDER = {
  CR: ['Assumption', 'Strengthen', 'Weaken', 'Evaluate', 'Inference', 'Paradox', 'Flaw', 'Method', 'Boldface', 'Complete the Passage'],
  RC: ['Main Idea', 'Detail', 'Inference', 'Function', 'Application', 'Tone', 'Vocabulary', 'Weaken'],
};

let _dataCache = null;
let _poolCache = null;
let _libraryCache = null;

function loadOgData() {
  if (_dataCache) return _dataCache;
  try {
    _dataCache = JSON.parse(fs.readFileSync(POOL_PATH, 'utf-8'));
  } catch (e) {
    _dataCache = { books: [] };
  }
  return _dataCache;
}

// Flatten the book/section nesting into one list of usable questions, each
// carrying the context the builder and the runner need: which book it came from,
// whether it is CR or RC, and for RC the passage object itself (text plus the
// structured `lines[]` the pdfplumber pass writes for gutter numbering).
function buildOgPool(data) {
  const questions = [];
  const byId = new Map();
  const passages = new Map();
  const books = [];

  for (const book of (data && data.books) || []) {
    books.push({ code: book.code, title: book.title });
    for (const section of book.sections || []) {
      for (const p of section.passages || []) passages.set(p.id, p);
      for (const q of section.questions || []) {
        if (!q.usable) continue;
        const enriched = {
          ...q,
          bookCode: book.code,
          bookTitle: book.title,
          kind: section.kind,
          passage: q.passageId ? (passages.get(q.passageId) || null) : null,
        };
        questions.push(enriched);
        byId.set(q.id, enriched);
      }
    }
  }
  return { questions, byId, passages, books };
}

// Facets for the set builder's dropdowns. Counts are over usable questions only,
// so a label showing 0 never appears.
function buildOgLibrary(pool) {
  const kinds = ['CR', 'RC'];
  const tally = (pred, pick, order = null) => {
    const counts = new Map();
    for (const q of pool.questions) {
      if (!pred(q)) continue;
      const key = pick(q);
      counts.set(key, (counts.get(key) || 0) + 1);
    }
    const rank = (label) => {
      if (label === UNLABELED || label === UNCLASSIFIED) return Number.MAX_SAFE_INTEGER; // the residue sorts last
      const i = order ? order.indexOf(label) : -1;
      return i >= 0 ? i : Number.MAX_SAFE_INTEGER - 1;
    };
    return [...counts.entries()]
      .sort((a, b) => (rank(a[0]) - rank(b[0])) || a[0].localeCompare(b[0]))
      .map(([label, count]) => ({ label, count }));
  };

  const typeLabels = {};
  const questionTypes = {};
  const difficulties = {};
  const totals = { CR: 0, RC: 0, passages: 0 };
  const usedPassages = new Set();

  for (const kind of kinds) {
    const inKind = (q) => q.kind === kind;
    typeLabels[kind] = tally(inKind, (q) => q.typeLabel || UNLABELED);
    // Ordered by the rule table's own order, so the list reads as a taxonomy
    // rather than alphabetically; the unclassified residue still sorts last.
    questionTypes[kind] = tally(inKind, (q) => q.questionType || UNCLASSIFIED, QUESTION_TYPE_ORDER[kind]);
    difficulties[kind] = tally(inKind, (q) => q.difficulty || UNLABELED, DIFFICULTY_ORDER);
    totals[kind] = pool.questions.filter(inKind).length;
  }
  for (const q of pool.questions) if (q.passageId) usedPassages.add(q.passageId);
  totals.passages = usedPassages.size;

  const books = pool.books
    .map((b) => ({
      code: b.code,
      title: b.title,
      counts: {
        CR: pool.questions.filter((q) => q.bookCode === b.code && q.kind === 'CR').length,
        RC: pool.questions.filter((q) => q.bookCode === b.code && q.kind === 'RC').length,
      },
    }))
    .filter((b) => b.counts.CR + b.counts.RC > 0);

  return { books, typeLabels, questionTypes, difficulties, totals };
}

function ogPool() {
  if (!_poolCache) _poolCache = buildOgPool(loadOgData());
  return _poolCache;
}

function ogQuestion(id) {
  return ogPool().byId.get(String(id)) || null;
}

function ogLibrary() {
  if (!_libraryCache) _libraryCache = buildOgLibrary(ogPool());
  return _libraryCache;
}

module.exports = {
  loadOgData, ogPool, ogQuestion, ogLibrary, buildOgPool, buildOgLibrary,
  UNLABELED, UNCLASSIFIED, QUESTION_TYPE_ORDER,
};
